### ISSUE TITLE
stage is ignored

### ISSUE THREAD

**Issue by zoellner** [ajmath/serverless-offline-scheduler#35]
I'm running the scheduler with
`sls schedule --stage local`
but get an error
`Error: Command failed: serverless invoke local --function SchedulerFunction --data {"schedule":"every-minute"}`
and before that some errors about it not being able to populate a few variables.
However, those variables shouldn't matter in the local stage. 
When I manually run
`serverless invoke local --function SchedulerFunction --data {"schedule":"every-minute"}`
I get the same error, however if I run 
`serverless invoke local --stage local --function SchedulerFunction --data {"schedule":"every-minute"}`
i.e. with my custom stage passed through, the function runs fine.

**Comment by ajmath** [comment]
Thanks for reporting. This should be fixed in #40 which is published in 0.4.1

**Comment by tomusiaka** [comment]
FYI [npm](https://www.npmjs.com/package/serverless-offline-scheduler) still shows 0.4.0 as the most recent version. Any plan on when 0.4.1 will be available?

**Comment by ajmath** [comment]
I think I mistakenly mentioned the wrong version number on my previous comment.  It was fixed in 0.4.0.  However, 0.4.1 which includes another fix was just published.

**Comment by tomusiaka** [comment]
Awesome. Thanks.
